debian12.2-slim, latest rspamd and gucci dependancies
mailserver2/debian-mail-overlay pull request #23
Opened 2023-12-12 16:59 UTC by diroots

fix https://github.com/mailserver2/debian-mail-overlay/issues/22

2023-12-12 22:11 UTC, AndrewSav requested changes

2023-12-12 22:11 UTC, AndrewSav commented on README.md
> +* Skalibs 2.14.0.1 : <https://skarnet.org/software/skalibs/>
This does not match the version in Dockerfile, which is `2.13.1.1`

2023-12-12 22:11 UTC, AndrewSav commented on README.md
> +* Execline 2.9.4.0 : <https://skarnet.org/software/execline/>
This does not match the version in Dockerfile, which is 2.9.3.0

2023-12-12 22:11 UTC, AndrewSav commented on README.md
> +* s6 2.12.0.2 : <https://skarnet.org/software/s6/>
This does not match the version in Dockerfile, which is 2.11.3.2

2023-12-12 22:47 UTC, AndrewSav commented
Looking good to me, let's get these versions sorted, then I'll run it for a week with the new image (we will also need a mailserver PR for that I'm guessing) and then we can merge.

2023-12-13 21:12 UTC, diroots commented
i did update the dockerfile so all versions are aligned @AndrewSav

2023-12-13 21:26 UTC, diroots commented
ok i think i know why the 3 skarnet dependancies were not updated in the dockerfile, but in the readme : i did run the 'update-dependencies.sh script with bash instead of zsh and it could not do the string replacements in the dockerfile, it did only in the readme file. fully fixed now

2023-12-14 09:06 UTC, AndrewSav commented
@diroots thank you for this. Have you tested this? If so I think I'll just merge it without testing because we can test it when we do the PR for the mailserver repo, but I'd like to know if you ran it and it worked for you

2023-12-14 09:06 UTC, AndrewSav approved these changes

2023-12-14 09:08 UTC, diroots commented
i did not run this as is yet. i did update postfix and clamav from with container to the latest version from debian repo, and i did test the update to rspamd 3.7.4 with adding the repo in the container and install it from there. 

all seemed to work when restarting container with these versions

2023-12-14 09:14 UTC, diroots commented
i would also say it 'safe' to merge, so it could biuld the underlying debian-mail-overlay image. 

then we could test to spin up a mailserver container based on that, on a test env / branch

2023-12-14 19:43 UTC, AndrewSav commented
@diroots we are building/pushing the image manually. I'll try to find time to work on this over the weekend

2023-12-15 10:27 UTC, diroots commented
@AndrewSav 
- i did build a mailserver based on this new image. 
- i did deploy this mailserver on one of our staigng env. upgrade from previous 1.1.15 version went seamlessly, and the stack is running as expected. i can see updated rspamd/postfix/clamav. all these service logs show it runs smoothly as it was before.

2023-12-15 19:06 UTC, merged